# -*- coding: utf-8 -*-
"""ML_HT_AICourse_Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d1xKiusONbB_-lDAI1UqyPGVqgyHoOXG

# Аналитика и предсказание выживаемости на Титанике

## План

- Загрузка и базовое исследование данных

- Построение модели машинного обучения

## Подключение зависимостей / Загрузка библиотек
"""

import pandas as pd # для работы с таблицами
import numpy as np # для эффективных вычислений
import matplotlib.pyplot as plt
import seaborn as sns # для построения графиков

"""# Загрузка и базовый анализ данных

Загрузим данные с помощью библиотеки ```pandas```, она же - ```pd``` в нашем примере. Для этого используем стандартный метод ```.read_csv(..)```, принимающий на вход путь к файлу с данными.

Загружаем данные о пассажирах Титаника по ссылке
"""

url = "https://raw.githubusercontent.com/Murcha1990/datasets/main/Titanic.xlsx"
df = pd.read_excel(url)

"""Анализ данных и, вообще их исследование, начинается с того, что просто глазами смотрим на то, что находится внутри .csv файлов. Для этого достаточно вывести на экран первые несколько строк загруженных таблиц.

Метод ```.head()``` поможет нам в этом. С его помощью печатаем первые 5 строк из нашей таблицы:
"""

df.head()

"""## Задание 1

Посмотрите на размер таблицы `df`.
Сколько строк в таблице?
"""

# ваш код здесь
df.shape

"""Оценим уровень выживаемости"""

df['Survived']

"""## Задание 2

Какая доля пассажиров Титаника выжила? Ответ округлите до сотых.
"""

# ваш код здесь
df['Survived'].value_counts(normalize=True)

"""Можно вычислять различные числовые характеристики столбцов.

Выше мы вычисляли среднее значение так:
`df['Survived'].mean() # доля выживших на Титанике`.

Аналогично, поставив после точки
* `max()`

* `min()`

* `median()`

можно вычислить максимум, минимум и медиану набора данных.

### Задание 3

Вычислите максимальный возраст пассажиров Титаника.
"""

# ваш код здесь
df['Age'].max()

"""### Задание 4

Вычислите средний возраст пассажиров Титаника.

Затем вычислите средний возраст пассажиров только 1 класса.

Верно ли, что пассажиры 1 класса в среднем более возрастные, чем по всему Титанику?
"""

# ваш код здесь
mask = df['Pclass'] == 1
df['Age'].mean() < df['Age'][mask].mean()

"""# Машинное обучение

Сделаем следующие шаги:

* Сначала нужно разбить данные на тренировочную и тестовую части

* На тренировочных данных обучить модель

* На тестовых данных применить ее и получить прогнозы

* На тестовых данных оценить качество модели

Сначала отделим признаки от целевой переменной:
"""

y = df['Survived'] # вектор целевой переменной

X = df.drop('Survived', axis = 1) # матрица объект-признак

X.head()

"""Заполним пропуски в данных"""

df.describe()

mean_age = X['Age'].mean()

X['Age'] = X['Age'].fillna(mean_age)

"""При помощи функции `train_test_split` разбейте данные на тренировочную и тестовую части в пропорции 7 к 3. Зафиксируйте `random_state=42`."""

from sklearn.model_selection import train_test_split

# ваш код здесь
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.25, random_state=42)

"""Обучите модель CatBoostClassifier на тренировочных данных по аналогии с кодом из [примера](https://colab.research.google.com/drive/1V2VSoyAXHwx63QNVoQK6F6oQbRTGbhz4?usp=sharing).

- Сначала создайте `cat_features` - список категориальных признаков
- Объявите модель CatBoostClassifier и передайте в нее cat_features; остальные параметры оставьте по умолчанию, то есть не задавайте
- Обучите модель на тренировочных данных
"""

cat_features = X.select_dtypes(include=["object"]).columns.to_list() # ваш код здесь

cat_features

"""Заполним пропуски в категориальных столбцах пустыми строками."""

for col in cat_features:
    Xtrain[col] = Xtrain[col].astype(str).fillna("")
    Xtest[col] = Xtest[col].astype(str).fillna("")

"""Обучаем модель:"""

!pip install catboost -q

from catboost import CatBoostClassifier

# ваш код здесь
model = CatBoostClassifier(iterations=100,
                          depth=2,
                          learning_rate=0.1,
                          loss_function='Logloss',
                          eval_metric='AUC',
                          cat_features=cat_features,
                          verbose=False)


# ваш код здесь
model.fit(Xtrain, ytrain)

pred_test = model.predict(Xtest) # предсказание классов

"""## Задание 5

- Сделайте прогноз целевой переменной на тестовых данных при помощи обученной модели

- Посчитайте долю правильных ответов модели. Это можно сделать вручную, а можно использовать готовую функцию `accuracy` (доля правильных ответов).

Метрику необходимо вычислять на тестовых данных. Ответ округлите до десятых.
"""

from sklearn.metrics import accuracy_score

# ваш код здесь
accuracy_score(ytest, pred_test)